### ISSUE TITLE
Meeting Notes 10/13

### ISSUE THREAD

**Issue by Starnite** [ericmjl/protein-systematic-characterization#38]
Todo:
- [x] Replicate pol assay
- [x] Hacky-taq with PB2 part 1 and part 2
- [x] cpec with both PB2 parts mutated and backbone (amplified with phusion)
- [ ] hierarchical bayesian modeling 

Write proposal
- [x] Outline by 10/20
- [x] Draft by 10/27
- [x] Submit by 11/3

**Comment by ericmjl** [comment]
ping @Starnite: don't forget to put in a PR for your coming goals!

**Comment by ericmjl** [comment]
Goals accomplished here, LGTM. Going to close this issue.
